# Generated by Django 6.0.5 on 2026-05-12 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('entry_type', models.CharField(choices=[('inward', 'Inward'), ('outward', 'Outward')], max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Entry Created'), ('physical_received', 'Physical Document Received'), ('forwarded', 'Forwarded'), ('received_by_department', 'Received by Department'), ('in_progress', 'In Progress'), ('action_taken', 'Action Taken'), ('closed', 'Closed'), ('returned', 'Returned'), ('on_hold', 'On Hold'), ('missing_physical_copy', 'Missing Physical Copy')], default='created', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_documents', to='documents.department')),
                ('destination_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_documents', to='documents.department')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='documents.department')),
                ('source_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='documents.zone')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('physical_received', 'Physical Received'), ('forwarded', 'Forwarded'), ('received', 'Received'), ('status_updated', 'Status Updated'), ('closed', 'Closed'), ('returned', 'Returned'), ('comment_added', 'Comment Added')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='documents.document')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from', to='documents.department')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to', to='documents.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
