# Generated by Django 6.0.5 on 2026-06-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_head_office_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Letter', 'Letter'), ('Memo', 'Memo'), ('Application', 'Application'), ('Report', 'Report'), ('Complaint', 'Complaint'), ('Other', 'Other')], max_length=100),
        ),
    ]
