# Generated by Django 6.0.5 on 2026-06-11 10:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_area_division_document_source_area_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='outward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='document',
            name='outward_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='outward_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='outward_quantity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CourierRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['description', 'quantity'],
                'unique_together': {('description', 'quantity', 'amount')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='courier_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.courierrate'),
        ),
    ]
