# Generated by Django 6.0.5 on 2026-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_outward_amount_document_outward_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_branch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='external_organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='external_organization_type',
            field=models.CharField(blank=True, choices=[('pksf', 'PKSF'), ('mra', 'MRA'), ('bank', 'Bank'), ('other', 'Other Organization')], max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
        ),
    ]
