# Generated by Django 6.0.5 on 2026-06-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_external_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
