# Generated by Django 6.0.5 on 2026-06-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='external_organization_type',
            field=models.CharField(blank=True, choices=[('pksf', 'PKSF'), ('mra', 'MRA'), ('bank', 'Bank'), ('government_offices', 'Government Offices'), ('other', 'Other Organization')], max_length=30),
        ),
    ]
