# Generated by Django 6.0.5 on 2026-06-23 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_external_organization_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmovement',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('physical_received', 'Physical Received'), ('forwarded', 'Forwarded'), ('received', 'Received'), ('delegated', 'Delegated'), ('status_updated', 'Status Updated'), ('closed', 'Closed'), ('returned', 'Returned'), ('comment_added', 'Comment Added')], max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('delegated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_delegations_cancelled', to=settings.AUTH_USER_MODEL)),
                ('delegated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_delegations_created', to=settings.AUTH_USER_MODEL)),
                ('delegated_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_delegations_received', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='documents.document')),
                ('original_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_delegations_as_original', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delegated_at'],
                'indexes': [models.Index(fields=['document', 'is_active'], name='documents_d_documen_acd017_idx'), models.Index(fields=['delegated_recipient', 'is_active'], name='documents_d_delegat_e0d448_idx'), models.Index(fields=['original_recipient', 'is_active'], name='documents_d_origina_9d4725_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDelegationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('backup_receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_delegation_backups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_temporary_delegation_rules', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_delegation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', 'start_date', 'end_date'], name='documents_u_user_id_dd2756_idx'), models.Index(fields=['backup_receiver', 'is_active'], name='documents_u_backup__fa656c_idx')],
            },
        ),
    ]
